/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.14.v202310241606.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V0_COMMONAPI_HANDLER_MSG_EXTER_SOMEIP_STUB_ADAPTER_HPP_
#define V0_COMMONAPI_HANDLER_MSG_EXTER_SOMEIP_STUB_ADAPTER_HPP_

#include <v0/commonapi/Handler_msg_exterStub.hpp>
#include <v0/commonapi/Handler_msg_exterSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {

template <typename _Stub = ::v0::commonapi::Handler_msg_exterStub, typename... _Stubs>
class Handler_msg_exterSomeIPStubAdapterInternal
    : public virtual Handler_msg_exterStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< Handler_msg_exterSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> Handler_msg_exterSomeIPStubAdapterHelper;

    ~Handler_msg_exterSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        Handler_msg_exterSomeIPStubAdapterHelper::deinit();
    }

    void fireHandlerStatusExterEvent(const int32_t &_statusCode);

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::commonapi::Handler_msg_exterStub,
        CommonAPI::Version
    > getHandler_msg_exterInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::commonapi::Handler_msg_exterStub,
        std::tuple< CommonAPI::ByteBuffer>,
        std::tuple< CommonAPI::ByteBuffer>,
        std::tuple< CommonAPI::SomeIP::ByteBufferDeployment>,
        std::tuple< CommonAPI::SomeIP::ByteBufferDeployment>
    > updateMsgExterStubDispatcher;
    
    Handler_msg_exterSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        Handler_msg_exterSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< Handler_msg_exterStub>(_stub)),
        getHandler_msg_exterInterfaceVersionStubDispatcher(&Handler_msg_exterStub::lockInterfaceVersionAttribute, &Handler_msg_exterStub::getInterfaceVersion, false, true),
        updateMsgExterStubDispatcher(
            &Handler_msg_exterStub::updateMsgExter,
            false,
            _stub->hasElement(0),
            std::make_tuple(static_cast< CommonAPI::SomeIP::ByteBufferDeployment* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::ByteBufferDeployment* >(nullptr)))
        
    {
        Handler_msg_exterSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x80e8) }, &updateMsgExterStubDispatcher );
        // Provided events/fields
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x81b0));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x9d08), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE);
        }
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void Handler_msg_exterSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireHandlerStatusExterEvent(const int32_t &_statusCode) {
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deployed_statusCode(_statusCode, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t> > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x9d08),
            false,
             deployed_statusCode 
    );
}


template <typename _Stub, typename... _Stubs>
void Handler_msg_exterSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {

}

template <typename _Stub, typename... _Stubs>
void Handler_msg_exterSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {

}

template <typename _Stub = ::v0::commonapi::Handler_msg_exterStub, typename... _Stubs>
class Handler_msg_exterSomeIPStubAdapter
    : public Handler_msg_exterSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    Handler_msg_exterSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          Handler_msg_exterSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace commonapi
} // namespace v0

#endif // V0_COMMONAPI_Handler_msg_exter_SOMEIP_STUB_ADAPTER_HPP_
