/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.14.v202310241606.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V0_COMMONAPI_OTA_INTER_SOMEIP_STUB_ADAPTER_HPP_
#define V0_COMMONAPI_OTA_INTER_SOMEIP_STUB_ADAPTER_HPP_

#include <v0/commonapi/OTA_interStub.hpp>
#include <v0/commonapi/OTA_interSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {

template <typename _Stub = ::v0::commonapi::OTA_interStub, typename... _Stubs>
class OTA_interSomeIPStubAdapterInternal
    : public virtual OTA_interStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< OTA_interSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> OTA_interSomeIPStubAdapterHelper;

    ~OTA_interSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        OTA_interSomeIPStubAdapterHelper::deinit();
    }

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::commonapi::OTA_interStub,
        CommonAPI::Version
    > getOTA_interInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::commonapi::OTA_interStub,
        std::tuple< CommonAPI::ByteBuffer, CommonAPI::ByteBuffer>,
        std::tuple< int32_t>,
        std::tuple< CommonAPI::SomeIP::ByteBufferDeployment, CommonAPI::SomeIP::ByteBufferDeployment>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<int32_t>>
    > pushUpdateStubDispatcher;
    
    OTA_interSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        OTA_interSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< OTA_interStub>(_stub)),
        getOTA_interInterfaceVersionStubDispatcher(&OTA_interStub::lockInterfaceVersionAttribute, &OTA_interStub::getInterfaceVersion, false, true),
        pushUpdateStubDispatcher(
            &OTA_interStub::pushUpdate,
            false,
            _stub->hasElement(0),
            std::make_tuple(static_cast< CommonAPI::SomeIP::ByteBufferDeployment* >(nullptr), static_cast< CommonAPI::SomeIP::ByteBufferDeployment* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr)))
        
    {
        OTA_interSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x7d00) }, &pushUpdateStubDispatcher );
        // Provided events/fields
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};


template <typename _Stub, typename... _Stubs>
void OTA_interSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {

}

template <typename _Stub, typename... _Stubs>
void OTA_interSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {

}

template <typename _Stub = ::v0::commonapi::OTA_interStub, typename... _Stubs>
class OTA_interSomeIPStubAdapter
    : public OTA_interSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    OTA_interSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          OTA_interSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace commonapi
} // namespace v0

#endif // V0_COMMONAPI_OTA_inter_SOMEIP_STUB_ADAPTER_HPP_
