/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.14.v202310241605.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_COMMONAPI_Handler_msg_exter_STUB_HPP_
#define V0_COMMONAPI_Handler_msg_exter_STUB_HPP_

#include <functional>
#include <sstream>




#include <v0/commonapi/Handler_msg_exter.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <unordered_set>
#include <vector>


#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service Handler_msg_exter. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class Handler_msg_exterStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual Handler_msg_exter {
 public:
    /**
    * Sends a broadcast event for handlerStatusExter. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireHandlerStatusExterEvent(const int32_t &_statusCode) = 0;


    virtual void deactivateManagedInstances() = 0;


protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for Handler_msg_exter.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class Handler_msg_exterStubRemoteEvent
{
public:
    virtual ~Handler_msg_exterStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service Handler_msg_exter to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class Handler_msg_exterStub
    : public virtual CommonAPI::Stub<Handler_msg_exterStubAdapter, Handler_msg_exterStubRemoteEvent>
{
public:
    typedef std::function<void (CommonAPI::ByteBuffer _udsResponse)> updateMsgExterReply_t;

    virtual ~Handler_msg_exterStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 2);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// This is the method that will be called on remote calls on the method updateMsgExter.
    virtual void updateMsgExter(const std::shared_ptr<CommonAPI::ClientId> _client, CommonAPI::ByteBuffer _udsRequest, updateMsgExterReply_t _reply) = 0;
    /// Sends a broadcast event for handlerStatusExter.
    virtual void fireHandlerStatusExterEvent(const int32_t &_statusCode) {
        auto stubAdapter = CommonAPI::Stub<Handler_msg_exterStubAdapter, Handler_msg_exterStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireHandlerStatusExterEvent(_statusCode);
    }


    using CommonAPI::Stub<Handler_msg_exterStubAdapter, Handler_msg_exterStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<Handler_msg_exterStubAdapter, Handler_msg_exterStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<Handler_msg_exterStubAdapter, Handler_msg_exterStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef Handler_msg_exterStubRemoteEvent RemoteEventType;
    typedef ::v0::commonapi::Handler_msg_exter StubInterface;
};

} // namespace commonapi
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_COMMONAPI_Handler_msg_exter_STUB_HPP_
