/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.14.v202310241605.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_COMMONAPI_Handler_msg_STUB_DEFAULT_HPP_
#define V0_COMMONAPI_Handler_msg_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v0/commonapi/Handler_msgStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v0 {
namespace commonapi {

/**
 * Provides a default implementation for Handler_msgStubRemoteEvent and
 * Handler_msgStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT Handler_msgStubDefault
    : public virtual Handler_msgStub {
public:
    COMMONAPI_EXPORT Handler_msgStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(Handler_msg::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT Handler_msgStubRemoteEvent* initStubAdapter(const std::shared_ptr< Handler_msgStubAdapter> &_adapter) {
        CommonAPI::Stub<Handler_msgStubAdapter, Handler_msgStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual void pushUpdate(const std::shared_ptr<CommonAPI::ClientId> _client, CommonAPI::ByteBuffer _firmware, CommonAPI::ByteBuffer _signature, pushUpdateReply_t _reply) {
        (void)_client;
        (void)_firmware;
        (void)_signature;
        int32_t result = 0;
        _reply(result);
    }
    COMMONAPI_EXPORT virtual void fireHandlerStatusEvent(const int32_t &_statusCode) {
        Handler_msgStub::fireHandlerStatusEvent(_statusCode);
    }


protected:
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual Handler_msgStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(Handler_msgStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        Handler_msgStubDefault *defaultStub_;
    };
protected:
    Handler_msgStubDefault::RemoteEventHandler remoteEventHandler_;

private:


    CommonAPI::Version interfaceVersion_;
};

} // namespace commonapi
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_COMMONAPI_Handler_msg_STUB_DEFAULT
